# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.setDeviceIdentifier(UIDevice.currentDevice.uniqueIdentifier)
  TestFlight.takeOff('a574aad2bf1a00f2ebd7f2c501c61ce7_MjQ2OTk2MjAxMy0wNy0xMCAyMjo1Mzo1MS42NDgyMTE')
  end)
end
